language: java
deploy:
  provider: heroku
  api_key:
    secure: JPe93Q2c8fuBjdWqAmx7dJ37/NK7urMLUSPcL3/cMvevWMLWPh+RMGrDH3MNUnV5eUFB9VpOrMjZ5+3j7RrZFaUCgmdgAXYDPTKj6rKQcyh4O6Zf2PV86pSJ3Ydnxtzy4on7upc6wpHMnG5SNvWbx+Q9W6MLjmyi4Zcn0b4A0HxV6emSXzWyTghQZ9OU7nAtnahubRkUib5bLgmSaIACghJhCdQoPqeQe3oGEy4JMPl2VfeDUnaxtYz9jkO3QKFagP409q51gVz2JL/Q3+eeUEIwv5niQAk9SJPZQEJXvbYYL6/E1Jvi330OfT2ywtvPxNx5vzi7EkPpNNdUtaZnQOnvB+1Mg/c85mKmojNDYu2nvPjtWoYRWQbAU780fJDuogDBzRO/s7w3lI/vOA0SkWSn3UqW1W4NNdH5KljLTPdY54bfvhTQ+h9UteZaJX3CTc91lulWCnXM7/CjAX06ullcvmshnemlpXXqq2qxUYUNsyIlz9800fBuQq7iFVZ09x+qAe90v8sKDdb5TscQETu1uDzDtHQUxVhKsHrh6zCqH2NtnL+oxUD/OKM30rM7oipidW6MPxnsZYLg9vWRzAt667sw2UgKqtFH0jbp2cznRf16/eCUCcXAC6x/C/74sb32ds/BWx3thtzAa7sfArdJEGvXMUaB32feJHDGBS0=
    app: gentle-fjord-31786

