language: java
deploy:
  provider: heroku
  api_key:
    secure: LjOH044fjLG2WDO3zvsnmUZfqdR4w9b8cfQWywOftuGj7rh7ZcEFwDHKkpjNxSE2Nbz8w1qsilCmfSDuLAzRwBUVsTant0t+pjdaOKcQxsA0HpJcJBvj1jf9Xa+SbYTnfIZyPLmg/c8SwZndbmyp2bE30DoWt+n67iLtd8Si20T27Rr0oFD9lRXhrNxWpYgwF7esDeDIK8E7g5ryggdhOx3t2pwxaa1IAvtA2X+Pfr7ESFGBs4Pwb1bhLwkdGizzRsg9YdRdJa0IX+5641Xa7OxLK9suq+y0Bxa4SEt33UMsU/v5URXtc14XYlOMq6C9FoaESDG3DM9s0XRvhN34LA52IQYdY9Aj4Vl76P1bEyPUrSOC+CUR19Ozum6mImkG3JJ7lO9B2Sd0zyN64V3fB3i1jjlQsm/OzccE6J4C3ybvNdMsp3+Le1C69MCQw7zN51vw8uamT1nB/5PYgg9bSFtaYG+J5Pyn2kdYpOzZ+1TFfo3DZzGDhzuxlrB6u0wnYAy6AZgHU6h11QatRdWShr4BnNwYKlGfqEHuFAd+YPioJoY8uykhC2zuO9pX6ClNHACCYNjT3e7bYzjtBtGgtTybgvIW0phrvMKomnm9+Tyr06FhDw2WObvP/DYcBSng+hAlP5aaX3GPJMm5HBBcaWBgkW0HEgYXzrFpEtEdsGI=

