language: java
services:
- docker
script:
- bash docker_push.sh

env:
  global:
  - secure: Xd7+3p3OwT4gmj3MOkThTwJhSOj1E8LinUlGOWRQ7DTTwl7zinPu5umVo0LdiXxIQew+C9a+Rv+LHGhAI1j9EX0acEIwBojTjKUhubZzZDDD0wacF9KvqwgeuGa8d/RP4S5/umlxBiqzZBKh3d3ARKL9Dk5FeYrcBSPFR6iSPbMEEfFEz82WC5/amwajBkBA3VU9EQyAxl/E7cobzJc3/V6edVR8eGdIjNBZBfQxFpTKCT4d5w3WZoQl0OmbCEYrjR0Z+4t/Lq7C/f8mp28ANsBBFxvsypW64DST9+6KK6M8f4vVpHOiv8z/0WxQXnaoyxEOLTVJKCvp3vUtfZHsGkbSc1bo64+jxirFYaSJOjwuzitn11NBv01czskn+SdSNZsEmgj18V0Pp4e7CDgAXnR1BF+Er6XCK5NN27kT1DoD944RFvhceiDpUKz4P+qC4UcXGbI/KqfacDOTafM1Ty6GoZ/6K0arY0gQbtU1fsxWJ0WCkITv/R25R0sYD/zdOkLFlwzl2o1wLLzU/SxRqEeRaqpUU51umxssmGEE/suGV4GgpKu7EuS978nNNV7xu+AZwnHSEYID4Or+b3BZ+uk9z9k5r9Ck2tjxIRc6nAJKmnp97TrZKiWdi1DFXQbc067ODA09iexAqWFB8EO7gS7LzKnLQHvxif0mjt9jWHk=
  - secure: RMoNBuBhl6Ps/i6aMP5X+RvwsBO1xRRSLYrxAzsXFS68NpuKGOf/kZAG4wFh4a3q/pkeuWyJdKtZfLqd2niubDnNiRog+mTuCpHIXrcSTTjJ9MLvZ2pv0JXcwTUm30xiIcs8UGB7v+lsBTuY4btJwTe1XtlJgfugcRyTo1C6bMf9vCpoRpo6zMaloBliAxJ6s+02FLnFo+AaNDZmEG+GkHp7sgyLj2/2R6U3EvsHuHr308EJsAO9YKA2nc/UvHoxLqH5TI04YlhUa4K8LHLaIFuvGtheG7txSHB17sRT0h2Tch07bD1zAHlzSnSjfefG83KJjpd4pHxZhmULzIXVqpfFHGoSBO+k0llqufLSwOch7+5mT4udYJHrrImfHo2/yPsX6DUORH7hGlBeJaLCpIm6tgSGHXcoZKzwlTuCsGUhMzSexwm4xUhOw60cPsFpxk3jnqUZPpmspjErDGUj3xwSjjMy18F9mzRMVHPS2slVZOton+kkuMlp8Ht7q6MUBOMRWXC6kn9YPCtMIUiy4D1I+Ey2tHxU84RSLz6/wzlwhAbbqzlidjzvPwNFJPFsDbupUYleWQeKn3bnRVZFweyNBBOc8eQDmS0K8IVtsmLVz840ePePica82aL7OJiqQgmKzTeytGkt4oL6o+TyEIBabTDq17416M7HLuzulYQ=



